Debug compress_mov integration with dplyr, but still not solved. Deprecated to previous R implementation.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,8 @@
 set -x
 set -e
 
+DEBUG=1
+
 which cmake
 
 rm -rf _builds
@@ -14,6 +16,9 @@ cmake --build _builds --target install
 if [ "$(uname)" = "Darwin" ]; then
   cp _install/lib/libmovr.dylib src/libmovr.dylib || echo "Failed: libmovr.dylib -> src"
 elif [ "$(expr substr $(uname -s) 1 5)" = "Linux" ]; then
-  cp _install/lib/libmovr.so src/libmovr.so || echo "Failed: libmovr.so -> src"
-  cp _install/lib/libmovr.so src/movr.so # for the use of run_example()
+  if [ $DEBUG = 1 ]; then
+    cp _install/lib/libmovr.so src/movr.so # for the use of run_example()
+  else
+    cp _install/lib/libmovr.so src/libmovr.so || echo "Failed: libmovr.so -> src"
+  fi
 fi
